### ISSUE TITLE
[chore] Highlight docs which are draft, WIP, out-of-date, etc.

### ISSUE THREAD

**Issue by andrewnicols** [moodle/devdocs#83]
### What do we need to do?

Identify documents in various state in the front-matter and turn this into a page banner with links to contributing to docs, etc.         

For example:

```
---
title: Question bank
draft:
  issueNumber: 99
  trackerIssue: MDL-12345
tags:
  - draft
---
```

Could be turned into a banner which links to the devdocs issue with information, and the Tracker issue (if relevant), and provides links to the devdocs contributing docs, etc.

Similarly a Draft tag could warn users that this page is a draft and may not be complete, and to see issue # for more information or provide feedback.
